server:
  port: 38080

spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always            # 항상 SQL 초기화 실행
      schema-locations: classpath:sql/tour-ddl.sql  # 스키마 초기화 파일 위치
      data-locations: classpath:sql/tour-dml.sql # 데이터 삽입 파일 위치
  datasource:
    write:
      jdbc-url: jdbc:h2:~/h2db/tour;AUTO_SERVER=TRUE
      driver-class-name: org.h2.Driver
      username: tour
      password: qwer1234
      hikari:
        maximum-pool-size: 10
        connection-timeout: 30000
        minimum-idle: 5
        idle-timeout: 600000
        max-lifetime: 1800000
    read:
      jdbc-url: jdbc:h2:~/h2db/tour;AUTO_SERVER=TRUE
      driver-class-name: org.h2.Driver
      username: tour
      password: qwer1234
      hikari:
        maximum-pool-size: 10
        connection-timeout: 30000
        minimum-idle: 5
        idle-timeout: 600000
        max-lifetime: 1800000

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    com.lottecard.travel: DEBUG
    org.springdoc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE